### PR TITLE
Fix errors raised in release validation

### PR DESCRIPTION
**Pull request by kimadactyl**
- [Remove scrambled `<p>` tag](https://github.com/geeksforsocialchange/PlaceCal/pull/2414#issuecomment-2186880129)
- [Fix icon font](https://github.com/geeksforsocialchange/PlaceCal/pull/2485#issuecomment-2186890635)
- [Reduce weekly view limit to 50](https://github.com/geeksforsocialchange/PlaceCal/pull/2473#issuecomment-2188396964)

Screenshot 2024-06-25 at 12 01 05
Screenshot 2024-06-25 at 12 01 17

### CODE REVIEW

**Comment by katjam** [comment]
Strictly speaking we should raise an issue with these AC or a least tag this with the issue numbers where the problems were raised. Otherwise - this way, chaos lies...

**Comment by kimadactyl** [comment]
This has raised another tech debt job detailed here:

https://github.com/geeksforsocialchange/PlaceCal/issues/2517

**Review by katjam — APPROVED** [review]
Looks great.

**Comment by kimadactyl** [comment]
> Strictly speaking we should raise an issue with these AC or a least tag this with the issue numbers where the problems were raised. Otherwise - this way, chaos lies...

I have linked the comments I'm replying to? You don't think that's sufficient? Sorry just my time is evapourating as is I do wish we had more time for this obvi.

**Comment by kimadactyl** [comment]
Did regular merge so at least the commits are not blobbed together

**Comment by kimadactyl** [comment]
kim and honor confirmed all working on staging

**Pull request merged**
