### PR TITLE
Fix duplicate partners on partner index pages

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Implements #1427

### CODE REVIEW

**Comment by aaaaargZombies** [comment]
Tests run on my machine, manual testing by visiting the effected page showed no sign of the issue. I will start having a read of the code with the docs open so I can get an idea of whats going on. But as far as I can tell LGTM

**Review by aaaaargZombies — APPROVED** [review]
:+1:

**Comment by aaaaargZombies** [comment]
I'd be tempted to change the title from "Bug" to "Fix" but this is probably a matter of taste

**Comment by kimadactyl** [comment]
For this repo the idea is that they're sentances that can go straight into release notes but I don't think this is written down anywhere yet!

**Comment by kimadactyl** [comment]
Screenshot 2022-08-22 at 12 18 58

Confirmed working on staging - i reproduced the record and this seems to be because it had 3 service areas set it was showing up 3 times

**Comment by kimadactyl** [comment]
Oh crap. It's not respecting the tag filter at all now. I assumed this was a staging situation but... it is not. My bad for breaking this but we need this fixed asap...

Screenshot 2022-08-22 at 13 00 19

**Pull request merged**
