### PR TITLE
Use Prettier

### PR DESCRIPTION
**Pull request by erbridge**
Standards are good. They make code more consistent and readable and reduce the amount of effort spent talking about what code should look like. I like Prettier because it formats lots of different things and has strong opinions (so you don't have to), but I'm open to other choices. The only override I've learned to make is that [tabs are more accessible than spaces](https://twitter.com/Rich_Harris/status/1541761871585464323).

I've included a precommit hook in here, so you should basically never need to think about running it regardless of your code editor or setup or whatever.

## TODO

- [ ] Close partially completed #854
- [ ] Open a new issue for formatting Ruby
- [ ] Open a new issue for linting Ruby
- [ ] Open a new issue for linting JavaScript
- [ ] Open a new issue for linting stylesheets
- [ ] Open a new issue for running formatters and linters as part of running tests
- [ ] Open a new issue for running formatters and linters on CI

### CODE REVIEW

**Comment by kimadactyl** [comment]
Just to note we have a very old open issue #854 - would be nice if this PR expanded to cover this?

**Comment by erbridge** [comment]
Ah. We can also do Ruby stuff if we want. I feel like it's a different scope to this though? Happy to introduce Ruby formatting and CI enforcement alongside this if you think we need that for this to have any value?

**Comment by erbridge** [comment]
Or maybe I misunderstood actually @kimadactyl? Are you suggesting we close #854 and open more tightly scoped things or close this PR and open more tightly scoped PRs?

**Comment by kimadactyl** [comment]
I guess I'm saying this starts to fix #854 so we should either make this PR close it completely, OR merge this as is and open new tickets that are more tightly scoped?

In other words, I'm wary of merging this as is as it sort of half addresses a ticket we have and having it half fixed in this instance is maybe more annoying than having it all fixed :)

**Comment by kimadactyl** [comment]
Also @katjam will have opinions no doubt :)

**Comment by aaaaargZombies** [comment]
Looks like this has become more a discussion about process but I'll just add that I'd really like to have prettier setup, I find it really helps me reading the code and removes those tiny formatting decisions you might have to make when typing.

**Comment by kimadactyl** [comment]
Oh to be clear I'm happy to merge this - just we need to make sure the open tickets reflect the current truth when we do

**Comment by erbridge** [comment]
Definitely agree, Kim. Happy to do that after this gets merged.

**Comment by ivan-kocienski-gfsc** [comment]
Is this like rubocop? but for yaml, markdown and javascript?

**Comment by ivan-kocienski-gfsc** [comment]
also i looked over the diffs and it looks okay but an introduction to Prettier in the readme would be nice explaining a bit about what it does and how it fits within our (studio) workflow (is it something we run manually? does it run on the CI?)

**Comment by erbridge** [comment]
@ivan-kocienski-gfsc do you see that as something preventing this being merged or a bit of follow up to do? Quick answer there is that Git will run it for you pre-commit and otherwise you don't need to pay much attention to it.

And yes, it fills a similar role to Rubocop, but is focused on the code format aspects of style, and not the wider style like how long functions should be and what naming conventions to use for things.

**Review by katjam — APPROVED** [review]
Yes. I agree with this. We've had it on the backlog for ages. Very important now that so many people are working on the code together.

**Comment by ivan-kocienski-gfsc** [comment]
@erbridge I suppose I was saying that it'd be nice to have a short intro to Prettier and how it will work within PlaceCal. (For example I write about [workflow](https://github.com/GenderedIntelligence/gi-matrix#workflow) in gi-matrix in the README so people won't encounter things unexpectedly). Some type of heads up that this is a thing now. I would either put it in the readme, make a note in the PR commit and mention that on the PC discord channel or just announce it on the discord channel as a stand alone heads up that this is now a thing.

**Comment by katjam** [comment]
> @erbridge I suppose I was saying that it'd be nice to have a short intro to Prettier and how it will work within PlaceCal. (For example I write about [workflow](https://github.com/GenderedIntelligence/gi-matrix#workflow) in gi-matrix in the README so people won't encounter things unexpectedly). Some type of heads up that this is a thing now. I would either put it in the readme, make a note in the PR commit and mention that on the PC discord channel or just announce it on the discord channel as a stand alone heads up that this is now a thing.

This is a fair point, but also I think prettier is very industry standard at the moment. Good to have some doc on it because it may not be industry standard in the future too... but my opinion on README info is should be specific to this project so like "We use prettier to format our code. The config is here. (We use tabs because :) ) It runs on a pre-commit hook." good but explaining what prettier or howw it works should be left to the prettier docs (which we can link ot to)

**Comment by erbridge** [comment]
Right. I'll add a quick note to the Readme, merge this, and do a bunch of issue curation. Thanks folks.

**Review by katjam — APPROVED** [review]
Nice!

**Pull request merged**
