### PR TITLE
Add Bruno

### LINKED ISSUE #2520: Move API code examples inside codebase
## User story

As a developer I want an easy way to test the API, and I want the API examples to remain inside the codebase so they stay up to date.

## Acceptance criteria

- [ ] API examples from the handbook are in the codebase
- [ ] Requests generated by [Trans Dimension are documented](https://github.com/GenderedIntelligence/the-trans-dimension/tree/main/src/Data/PlaceCal) and have minimal testing
- [ ] README updated to show how to run them
- [ ] Handbook updated to point to the Bruno examples

## Implementation notes & questions

Plan is to use [Bruno](https://www.usebruno.com/) for this.

## Implementation plan

_To be written by the developer_

### PR DESCRIPTION
**Pull request by mickeymarse**
As discussed on Discord, I'm helping with the creations of the API requestions collections via [Bruno](https://www.usebruno.com/).

- Continuing from where @kimadactyl left, I've added a few more requests and polished some of the old ones.
- I am not experienced with GraphQL, so, please, feel free to leave feedback on all the queries.
- Ultimately, I guess it could be easier if you can let me know all the requests/endpoints you would like to check, since I don't know the repo and the project as mush as you do.

Fixes #2520

### CODE REVIEW

**Comment by kimadactyl** [comment]
Have a peak at the linked ticket to see the queries we are actually using in production, will help next week if it's not making sense :)

**Comment by mickeymarse** [comment]
My bad, I should've checked that. Thank you very much.
It seems doable. I will get back to you if I have further questions. 😊

**Comment by mickeymarse** [comment]
I've added, updated and renamed queries following the docs mentioned in the original issue.
Might be good to have a chat on Discord though when you have time.

**Comment by kimadactyl** [comment]
This is looking really great! Awesome going.

A few minor points:

- Let's move the hard coded vars into the [dedicated vars section](https://docs.usebruno.com/scripting/vars) so the queries are nice and clean?
- What's the diff between "All Events" and "Events Index"? I can see the queries are different but i think "index" is kinda a web-specific word that's a bit confusing? Can these have more descriptive titles?
- "Partner tag" should be called "Partnership" everywhere this is mentioned. "partnership" is a type of tag, this is one of the more confusing aspects of the code base, we are trying to stop referring to tags as it makes things more confusing!). The other types of tag are facility and category which are not really in use atm.
- Ditto "articles by tag" is really "articles in partnership" and "partners by tag" is "partners in partnership"

**Comment by katjam** [comment]
Thanks for picking this up. Feel free to tag me if you have questions or need a hand. As Kim says, no rush at all!

**Comment by mickeymarse** [comment]
>     * Let's move the hard coded vars into the [dedicated vars section](https://docs.usebruno.com/scripting/vars) so the queries are nice and clean?

Done. However, that function seems to be still buggy and there are a couple of unmerged PR on the Bruno repos, so it looks more confusing than it was before right now. I believe there are issues with the JS template literals interpolation.
Unless I didn't really get it, and I'm doing something wrong, of course. 

>     * What's the diff between "All Events" and "Events Index"? I can see the queries are different but i think "index" is kinda a website-specific word that's a bit confusing in this context? Can these have more descriptive titles?

The index ones are a paginated list, which, once looking at it again, seems just like a repetition of the Filter query.
So, I would remove it from both and add a Partners by Filter query if you agree with this.

>     * "Partner tag" should be called "Partnership" everywhere this is mentioned. "partnership" is a type of tag, this is one of the more confusing aspects of the code base, we are trying to stop referring to tags as it makes things more confusing!). The other types of tag are facility and category which are not really in use atm.
> 
>     * Ditto "articles by tag" is really "articles in partnership" and "partners by tag" is "partners in partnership"

If this was referring only to the title of the queries, I did it. Otherwise, not sure what you want me to rename.

Also, I'm now getting this error when trying to push my commits:

```bash
ERROR: Permission to geeksforsocialchange/PlaceCal.git denied to mickeymarse.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Hence, you're probably reading this without being able to see what I'm talking about.
Any idea why this is happening?

**Comment by kimadactyl** [comment]
Sounds great, good work!

> Hence, you're probably reading this without being able to see what I'm talking about. Any idea why this is happening?

Hmm - are you still logged in to git in the terminal?

I always get a bit confused when working on a forked version rather than just being a repo contributor. While we could just make you a repo contributor its nice for us to try out having change requests from outside the main repo too. I think git gets a bit confused though but fundamentally the PR should be from your github username not the gfsc one if that makes sense (im too hot!)

**Comment by mickeymarse** [comment]
> Hmm - are you still logged in to git in the terminal?
> 

Problem solved. I was pushing to the wrong branch. 🙃 
You can check the commits now.

**Comment by kimadactyl** [comment]
This is looking fantastic. I fucked up the staging server so we can't merge into main until the letsencrypt bot resets my ratelimit -- awesome work thankyou! Woo!

**Review by kimadactyl — APPROVED** [review]

**Comment by kimadactyl** [comment]
Not sure why the tests won't run. Gonna attempt turning it off and on again...

**Comment by kimadactyl** [comment]
Ok, this doesn't touch any actual business logic files so I'm bypassing branch protection this once. 

If it happens again with an external contributor, I think it might be something to do with our [token configuration](https://stackoverflow.com/questions/52200096/github-pull-request-waiting-for-status-to-be-reported).

Thanks @mickeymarse!! Congrats on your first merge!

**Pull request merged**
