### PR TITLE
Improved calendar importer feedback

### LINKED ISSUE #2305: [Bug]: It's not clear to users that their calendar is failing/ how to reimport it
This issue is about the error state for a calendar that has failed import

## Story
Maybe we could improve the UI around this again - some more informative text? A clearer definition of what the problem is and how it can be fixed by the admin user.

## Further Context
https://www.notion.so/gfsc/Kim-s-timeline-for-completion-12-3-24-d0e8ef7a03c44ba08e56d4477e3fea5d?pvs=4#bb7290e3d3e449df95bcd0cac435d34f

Blocked by #2304 which is the loading state for this UI component.

## Acceptance Criteria
- [x] Once saved, the status of the calendar is visible at the top of the page
- [x] I can see details about the status of my calendar near the lozenge
- [x] The details about status include lozenge, date updated, description (including notices & any error details)
- [x] Placement & design of error description annotices TBC... we might want to look at formatting notices as a separate issue
- [x] Once saved, I can always see re-import button & trigger re-import
- [x] I **cannot** schedule a timed import for my calendar

If the calendar has:
- [ ] Not finished importing - `in_queue` or `in_worker` (loading) lozenge & notice to check back in 10 minutes
- [ ] Event problem - `idle` (success) lozenge & I see notices for the failing events & a message suggesting I fix then re-import
- [ ] Invalid response - `error` (error) lozenge & notice to (TBC)
- [ ] Inaccessible feed - `bad_source` (error) lozenge & notice to (TBC)
- [ ] ActiveRecord error - `error` (error) lozenge & notice to (TBC)
- [ ] #2399

## Plan
- [x] Change status lozenge copy from (idle --> success, in_queue --> loading, in_worker --> loading, error --> error, bad_source --> error)
- [x] Button copy from "Queue for import now" to Re-import calendar
- [ ] more tbc...

Placement of status block:
image

Status block changes:
image

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Closes #2305 

Work in progress!

On calendar admin edit page
- Moved importer status to top of page.
- Removed Import Date field
- Improved messaging around idle, busy and error states
- Improved notice list
- "Re queue" button is more helpful if there are any problems

This is also shown on the 'show calendar' page.

Also updated calendar model so when calendars are pushed on to the queue they clear their notices.

## Idle
Screenshot_2024-04-17_12-05-43

## Busy
Screenshot_2024-04-17_12-06-06

## Idle with notices
Notices can appear on either error'd calendars or non-error'd calendars, so if there are any notices then they are shown. There is a count of the number of times an error occurred. If there are any notices then the "requeue" button "looks" like it is in an error state.
Screenshot_2024-04-17_12-06-27

## Error
Screenshot_2024-04-17_12-06-58

### CODE REVIEW

**Comment by kimadactyl** [comment]
If there's any way the failing events could have a link to the source url that would be great I think so people can be linked directly to where they have to fix it. Appreciate it's prob impossible for ical.

**Comment by kimadactyl** [comment]
"View this calendar" -> "View events" might make more sense too just for button text. Maybe it could use tabbed navigation too so theres a little "settings | events" subnav?

**Comment by ivan-kocienski-gfsc** [comment]
Those sound like good ideas, but I think a bit out of scope for this issue as it's just about importer UX and improving the messaging around those problems.

**Comment by kimadactyl** [comment]
i think those are all importer ux issues but understand if you dont want to cram any more in to this pr :)

**Comment by r-ferrier** [comment]
I've had a look at this.

Also as soon as I tried to import a calendar (using the event strategy) it errored:
Screenshot 2024-04-17 at 09 35 13

This is something probably for a product owner to think about, but my second thought on testing this was that it looks like this is the whole form on my screen - I would not know that I needed to scroll down to hit update calendar if I was making a change - it looks to me like 'import now' is the button to click after making edits here.

Screenshot 2024-04-17 at 09 37 42

Haven't managed to check anything else here yet because of the above error but it looked like the diagrams in the problem were requesting the import block to go above the view calendar button?

**Comment by katjam** [comment]
In terms of the button placement, yes, it was my suggestion to put it next to the import button, but I think it is also fine where it is. Not worth spending more time over it.

One change I would like though is to get the lozenge design back for the status. I think it doesn't stand out enough now with no styling. DIdn't the date also have a timestamp before that was styled nicely? I think both the human read 12 hours ago and the exact time will be useful for folks to debug.

**Comment by ivan-kocienski-gfsc** [comment]
Updated UX. Now looks like

## Idle
Screenshot_2024-04-17_12-05-43

## Busy
Screenshot_2024-04-17_12-06-06

## Idle with notices
Screenshot_2024-04-17_12-06-27

## Error
Screenshot_2024-04-17_12-06-58

**Comment by katjam** [comment]
That looks better. let's see what @honor-gfsc thinks about the copy. We can merge as is and raise a ticket to go through all new copy in one sweep on Monday?

**Comment by r-ferrier** [comment]
Sorry Ivan, but this just looks really weird to me.

Screenshot 2024-04-18 at 09 06 50

- The status is so tiny it's hard to read. It also is kind of part of a sentence? It doesn't look quite right. Maybe you could just roll back the line with the status tag on it to what we used to have?
- The `import now` button is grey, which is a colour usually used to denote that a button has been disabled - is there a reason for it not to be blue like all the other buttons in the admin?
- Why is the title 'importing' - 'import status' seemed much more descriptive to me? When I read 'importing' it feels like a statement about what is happening right now, as in, this calendar is currently importing.

Happy to talk about these things in a meeting if better - I'm just struggling to match this to the wireframes provided in the issue and the copy change to the title feels confusing.

**Review by r-ferrier — APPROVED** [review]

**Pull request merged**
