### PR TITLE
Database seeding script

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Works on #1478

- Cleans up migrations
- database seeding with `rails db:seed`
- fixes the bug with infinite redirects when the database is empty

### CODE REVIEW

**Review by r-ferrier — COMMENTED** [review]
Unfortunately I just can't get this to run. Whatever I do, I just get back the following warning:
`you have data in your DB! (Neighbourhood=5)`

If I don't run `db:setup` first it complains that there is no db, so I run that, and then regardless of whether I running `db:migrate` or `db:schema:load` (or even nothing) I get that error. 

Is there something else I'm maybe doing wrong? I've double checked and I'm confident I'm completely removing the database each time I try it.

**Comment by ivan-kocienski-gfsc** [comment]
Ah. Thanks for checking that. There are so many rails commands and they all differ in slightly different ways.

As I understand it `rails db:setup` does not run the migrations but instead loads the schema, which is defined in `db/schema.rb`. Now- do we want to run the migrations or load the schema? Not sure what the benefits or drawbacks are of each option (speed, maybe?).

The procedure I use is to run
```
rails db:drop # if it exists
rails db:create
rails db:migrate
rails db:seed
rails db:info # sanity check every thing is a-okay
```

The warning you are getting is because the seed script is verifying the database is empty (don't seed over pre-existing data).

If you have problems after running the migration the solution I used was to have this in another rails console:

```
User.destroy_all; Neighbourhood.destroy_all; Tag.destroy_all; Site.destroy_all; Partner.destroy_all; Calendar.destroy_all
```

**Comment by ivan-kocienski-gfsc** [comment]
I also just checked `./bin/setup` on my local machine from not having a database at all and it works also. This is the script mentioned in the README.

**Review by r-ferrier — CHANGES_REQUESTED** [review]
I think this works really well! I've opened a new issue to update the makefile so we can try defaulting to this setup now for local work. We can build on these seeds as we go to make ourselves a really useful little set. I have a couple of questions:

- would it be possible to add four place based sites and four interest based sites & have them marked as published, so that we can keep something occupying the homepage and find your placecal page?

- I'm still nervous about the migrations!  I have some I'll need to run after this PR. Is there any way you can test how a new migration will run against a copy of the production database once this PR has gone in?

**Comment by ivan-kocienski-gfsc** [comment]
My thinking here is to get this merged in as a base and then build on top of it by having follow on tasks for defining
- tags (#1661)
- neighbourhoods (i think rosie is doing work to this effect)
- sites
- partnerships

@r-ferrier As for your second comment what you want to do is re-image a fresh copy of production on your local machine and run `rails db:migrate:status` will show you which migrations have run and which will run on next deploy

**Review by r-ferrier — APPROVED** [review]
Ok great, that sounds like a good plan. I tested I could still make a migration locally too on a copy of the production db and all was happy.

**Pull request merged**
