### PR TITLE
Added filtering of partners and places for subsites.

### PR DESCRIPTION
**Pull request by crantok**
Implemented through a literal SQL join. I assume this is the
least maintainable way to do it. It works for now.

### CODE REVIEW

**Comment by crantok** [comment]
Small feature. (2 methods changed.) Let me know if this is too disgusting a way to do it. I'm still new to rails. Will merge on Wednesday morning if no one objects.

**Comment by kimadactyl** [comment]
Did you compare `app/controllers/admin/pages_controller.rb` @crantok?

**Comment by crantok** [comment]
This looks mergeable. @kimadactyl assigned this to @GabAlexandria for review. 'Files changed' shows very little now that I've got rid of the SQL. Shall I just merge it?

**Comment by kimadactyl** [comment]
Looks like a good start, few queries:

- What happens if site is not set? Think the first method will error out, I think better to use `find_by` here
- Time to prune the methods in the pages controller or no? Is that duplicated content?
- A test or two would be nice :)

**Comment by crantok** [comment]
Tried with no subdomain and with invalid and valid subdomains. The first two display the canonical site and the last one displays the filtered site. Happy to write tests. Will do so.

**Comment by crantok** [comment]
Added integration tests that checked for subsite filtering. Anyone want to take a look or shall I go ahead and merge?

@kimadactyl I'm not sure what you meant about the pages controller in your previous comment.

**Comment by kimadactyl** [comment]
@rultor merge

**Comment by crantok** [comment]
@rultor merge

**Pull request merged**
