### PR TITLE
Remove unused behaviors.site.js code

### LINKED ISSUE #1423: Replace `behaviors.site.js`
## User story

As a developer I need move JS functionality to stimulus or onto the backend so that it is predictable and easier to reason about.

## Acceptance criteria

- [ ] `behaviors.site.js` is deleted
- [ ] The undesirable input is not accessible to the user.

## Implementation notes & questions

- The only thing left in this file is a function that deletes some form fields
- It effects "Other neighbourhoods to include"
- [behaviors.site.js](https://github.com/geeksforsocialchange/PlaceCal/blob/main/app/javascript/src/behaviors/behaviors.site.js)
- This looks like it should be handled in the template but I'm sure there was a reason it wasn't
- part of #1389

## Implementation plan

Either a stimulus component or never render the input if it is not needed.

### PR DESCRIPTION
**Pull request by aaaaargZombies**
fixes #1423
It turns out someone had already done in the view but left the JS in, so an easy fix for me :)

### CODE REVIEW

**Comment by kimadactyl** [comment]
I'm good to cut stuff but let's leave a few tests where we go.

For e.g. #1413? Altho tbh this might be covered in datatables? I think just you know, any testing good here?

**Comment by aaaaargZombies** [comment]
This only effects the edit/new site form
I can add a test to make sure we don't render an imput for "main neighborhood" on the edit page though?

And see why this test is breaking!

**Comment by kimadactyl** [comment]
yeah fair i think test for cocoon working as thats what youre removing?

are you sure that code does nothing :)

**Comment by aaaaargZombies** [comment]
Noop I was wrong about it not doing anything - and about what I thought it did initially. 

At least the tests work!

**Comment by kimadactyl** [comment]
yeah tests ftw!!

**Pull request closed without merging**
