### PR TITLE
Change address relationships

### LINKED ISSUE #1615: [Bug]: partner address linked
## Description
quote from discord

so there's one contact who runs 2 groups - Queer Running Club & Pecs Education. When I change the address of one, it changes the address of the other. Any idea why this happens?
these are the correct addresses

Pecs Education is here:
Basis Ldn:
361-362 Warbuton street
E8 3RR

Queer Running Club is here;
Brunswick East
Ground Floor,
17 Amhurst Terrace,
Lower Clapton,
E8 2BT

only obvious link in the admin UI seems to be the shared admin
```
Partner admins
1 user can edit this partner
    [kole.fulmine@gmail.com](https://admin.placecal.org/users/111/edit)
```
## Steps to reproduce

1. What you did first
1. What you did next

## What you expected to happen

What would you like to happen instead?

## Platform (if relevant)

What device and browser were you using?

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Fixes #1615 

Partners no longer share addresses

### CODE REVIEW

**Comment by aaaaargZombies** [comment]
Migration ran successfully

```
$rails db:migrate

== 20230103155804 FixPartnerAddressDuplicates: migrating ======================
== 20230103155804 FixPartnerAddressDuplicates: migrated (2.1937s) =============

Loading application environment...
Loading code in search of Active Record models...
Generating Entity-Relationship Diagram for 45 models...
Warning: Ignoring invalid model CollectionEvent (table collection_events does not exist)
Warning: Ignoring invalid model ActionMailbox::InboundEmail (table action_mailbox_inbound_emails does not exist)
Warning: Ignoring invalid model ActiveStorage::Attachment (table active_storage_attachments does not exist)
Warning: Ignoring invalid model ActiveStorage::Blob (table active_storage_blobs does not exist)
Warning: Ignoring invalid model ActiveStorage::VariantRecord (table active_storage_variant_records does not exist)
Warning: Ignoring invalid model ActionText::RichText (table action_text_rich_texts does not exist)
Warning: Ignoring invalid association :invited_by on User (polymorphic interface InvitedBy does not exist)
Done! Saved diagram to ./erd.pdf
```

No partners with duplicate `address_id` when queried from console

```
irb(main):001:0> Partner.group(:address_id).count(:address_id).keep_if{ |key, val| val > 1}
   (1.6ms)  SELECT COUNT("partners"."address_id") AS count_address_id, "partners"."address_id" AS partners_address_id FROM "partners" GROUP BY "partners"."address_id" => {}
 ```
 Tests passed and I logged in to the admin panel, created a new partner with the same address as an existing one. Made changes and they didn't effect each other.
  
So seems like it's worked!

**Comment by ivan-kocienski-gfsc** [comment]
Addresses are used in 3 areas:
1. Assigning an address to a partner in the admin UI.
2. Importing events (if the event has an address can that be mapped onto a partner?)
3. (event/partner) Scoping for sites/tags

**Comment by ivan-kocienski-gfsc** [comment]
So to answer my questions

1. assigning one address to each partner is not a problem for the UI (it does present a problem in that users cannot remove an assigned address)

2. Importing events. Unknown.
in [EventResolver](https://github.com/geeksforsocialchange/PlaceCal/blob/1625-change-address-relationships/app/jobs/calendar_importer/event_resolver.rb) `event_strategy` and `event_override_strategy` both call `Address.search` which returns an address match (that would be unique) so it only returns ONE address. Given multiple addresses now exist those strategies my behave in an undesirable way.

3. Scoping should be fine as the relationship chain from site to partner goes through Site->Neighbourhood->Address->Partner and if there are multiple addresses per partner that should not matter to Postgres.

**Review by aaaaargZombies — APPROVED** [review]
I'm still getting these warnings in the tests

```
PlaceCal/test/models/partner_test.rb:62: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
~/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-6.1.7/lib/active_record/suppressor.rb:47: warning: The called method `save!' is defined here
```

But I'm approving because it does solve the issue and I don't want to hold this up for people using placecal

**Pull request merged**
