### PR TITLE
Remove seed migrations gem and start new seeding system

### PR DESCRIPTION
**Pull request by erbridge**
Start of work against: 

- https://github.com/geeksforsocialchange/PlaceCal/issues/1463
- https://github.com/geeksforsocialchange/PlaceCal/issues/1371

### CODE REVIEW

**Comment by kimadactyl** [comment]
This is maybe a bit in the weeds but it would be very nice to have a map of Normal Island you can refer to when writing tests - sounds silly but I think having a concrete visualisation will help people no end

**Comment by erbridge** [comment]
This was mainly so I could actually run PlaceCal without having a production data dump, which I realised was why I was stuck in a redirection loop.

**Comment by ivan-kocienski-gfsc** [comment]
Looks like [this](https://github.com/geeksforsocialchange/PlaceCal/blob/main/db/migrate/20211203153422_correct_datamodel_by_importing_neighbourhoods_json.rb) is where Neighbourhoods get loaded in

**Comment by kimadactyl** [comment]
> Looks like [this](https://github.com/geeksforsocialchange/PlaceCal/blob/main/db/migrate/20211203153422_correct_datamodel_by_importing_neighbourhoods_json.rb) is where Neighbourhoods get loaded in

Ok but this ticket is explicitly **not** addressing neighbourhoods, it's just getting a basic seed system up and running

**Comment by ivan-kocienski-gfsc** [comment]
Hmm perhaps I am misunderstanding terminology here: to me seeding a database is where you have nothing in the db and load all the sample data in that a dev will typically need day to day. 

So we assume the migration populates neighbourhood and then never touch that table again?  Okay.

Perhaps the original issue could describe what needs to be seeded like:

- Create Users, Site, Tags, Partners
- Link User to Site and different User to Partner
- Maybe make Online Partner, Address Partner and Service Area Partner (and Tag Partner?)
- Create Calendar
- Create some events linking Partner to Site. ( <-- could be tricky)

**Comment by kimadactyl** [comment]
I don't think you're misunderstanding, you're just trying to fix everything in one go.

The goal here is to just improve it on how it is now - i.e. take out the seed migrations gem and make seeding a user actually work.

We don't have to eat the whole elephant in one bite! Each of those other steps is correct but is an additional ticket.

**Comment by ivan-kocienski-gfsc** [comment]
Just so you know if you run `bin/setup` it will drop the database and bring it back up from schema (and then run the seeds). This means there is an empty database with no neighbourhoods.

**Comment by kimadactyl** [comment]
Ahh that's a big gotcha and we should add a warning for that.

I don't think this needs any extra features tho! We can just merge it when the tests pass. We should be adding the seed files a bit more conciously IMO.

**Comment by kimadactyl** [comment]
Closed but remade in other PR to avoid annoying git issues

**Pull request closed without merging**
