### PR TITLE
update footer content design

### LINKED ISSUE #1823: Implement footer with agreed content
## Acceptance criteria

- [x] only the GFSC logo links out from the placecal website
- [x] privacy policy looks like a link not part of the address
- [x] upper links are reduced down to the following as per screenshot
    - email
    - admin login
    - join
- [x] footer should take inspiration from Marks [wireframes](https://xd.adobe.com/view/d737e480-ff3a-4e07-8d32-339f902ddf4b-8264/screen/60498a69-b830-493f-b479-476c90ebfb13/specs/) but does not need to implement exactly
- [x] update copyright date
- [x] add lankelly chase logo to sponsors 

## Implementation notes & questions 

footer notes

@studiosquid will redesign the footer. Maybe retain main nav?

split off from #1810

## Implementation plan

- there is no specific design for the current content I will use [Footer A](https://xd.adobe.com/view/d737e480-ff3a-4e07-8d32-339f902ddf4b-8264/screen/60498a69-b830-493f-b479-476c90ebfb13/specs/) as reference, replacing the repeated main nav with the upper links.
- I expect there to be a first draft followed by feedback in PR on visuals
- I will not implement the site navigation in the footer

### PR DESCRIPTION
**Pull request by aaaaargZombies**
fixes #1823 

## Description

Mostly followed the spirit of [Footer A](https://xd.adobe.com/view/d737e480-ff3a-4e07-8d32-339f902ddf4b-8264/screen/60498a69-b830-493f-b479-476c90ebfb13/specs/). The main change is the increased font size for the headers, this was failing to meet contrast thresholds at a smaller size. If we'd like to drop them down we'd need to change the color.

This should perhaps be converted to the new component system but we'd need to get Rosie's PR merged in first.

mobile

Screenshot 2023-05-03 at 17-12-39 PlaceCal The Community Calendar

tablet

Screenshot 2023-05-03 at 17-09-28 PlaceCal The Community Calendar

desktop

Screenshot 2023-05-03 at 17-09-09 PlaceCal The Community Calendar

### CODE REVIEW

**Comment by aaaaargZombies** [comment]
Looks like about an hour ago there was a request to

- add lankly chase to sponsors (@studiosquid I'm happy extract the SVG from the site unless you've already done it)
- login -> Admin login

I'll work on those as "request changes"

**Comment by kimadactyl** [comment]
i updated the issue for you too sorry i forgot to mention!

**Comment by studiosquid** [comment]
I've posted a PNG in the request Kim made yesterday, but if you're able to successfully extract the SVG and colour switch it that's great (I found the SVG difficult to work with as it has some embedded raster details). Have reattached the PNG here.

LankellyChase

**Comment by aaaaargZombies** [comment]
Mobile with requested changes

Screenshot 2023-05-04 at 10-52-30 PlaceCal The Community Calendar

**Comment by aaaaargZombies** [comment]
Mobile with added `hr` tag

Screenshot 2023-05-04 at 14-38-48 PlaceCal The Community Calendar

Now in view component form!

**Comment by r-ferrier** [comment]
@aaaaargZombies is this ready for a code review?

**Review by r-ferrier — APPROVED** [review]
I had a look at this earlier while it was still a mountain view component but it's so nice to review changes that are all clean shiny new files! They all look good to me.

**Pull request merged**
