### PR TITLE
fix: reduce event limit to switch to weekly view a touch

### PR DESCRIPTION
**Pull request by kimadactyl**
I think this is a little high atm and feedback from organisers has been wanting to switch earlier.

At some point we can add in a feature to pick this manually but for now let's just knock it down a touch.

### CODE REVIEW

**Review by katjam — APPROVED** [review]
Good call. Let's do a release in a couple weeks.

**Comment by honor-gfsc** [comment]
I still think 150 is really high, and without manually counting I don't know how to verify this.

**Comment by kimadactyl** [comment]
what would you prefer?

**Comment by honor-gfsc** [comment]
like 20!! a page worth!

**Pull request merged**
