### PR TITLE
Feature: Not Found page

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Fixes: #1407 

When an ActiveRecord resource can't be located, show a user friendly page.

### CODE REVIEW

**Comment by kimadactyl** [comment]
Will this also fix #1408?

Looks good to me tho! Can't believe this is was issue all along, lol.

**Comment by ivan-kocienski-gfsc** [comment]
Unfortunately not. Assets are served outside of the app so only missing resources will get covered by this fix

**Review by aaaaargZombies — APPROVED** [review]
OK I'm approving because it delivers the not found page nicely when we don't have the resource for the matching ID. I assume this is good enough for roll bar but I can't see the actual errors it's producing.

**Comment by kimadactyl** [comment]
Confirmed working but only for events - will open new tickets for other errors

Screenshot 2022-10-31 at 11 46 07
Screenshot 2022-10-31 at 11 46 01

**Comment by kimadactyl** [comment]
Ah its here already: https://github.com/geeksforsocialchange/PlaceCal/issues/759

**Pull request merged**
