### PR TITLE
Contact fields return null instead of error if they are blank

### LINKED ISSUE #2474: [Bug]: Contact information data is not always feeding through to graphql
## Description

View contact details on Trans Dimension for Material Grrrlz

There are more notes in the TransDim repo. Don't have time to write out here now, but basically need to chack what data is coming out of the graph QL so we know whether it's a fornt or backend issue

### PR DESCRIPTION
**Pull request by kimadactyl**
For input: 

```sh
curl -v -H "Content-Type: application/json" -d '{"query": "query { partner(id: 289) { id summary url contact { name email telephone } } }" }' https://placecal.org/api/v1/graphql
```

**Before**

```json
{
  "data": {
    "partner": {
      "id": "289",
      "summary": "Material Grrrlz is a community of fiber artists dedicated to celebrating the work of young women \u0026 queer people💗",
      "url": "https://www.materialgrrrlz.com/about-us",
      "contact": null
    }
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Contact.email"
    }
  ]
}
```

**After**

```json
{
  "data": {
    "partner": {
      "id": "289",
      "summary": "Material Grrrlz is a community of fiber artists dedicated to celebrating the work of young women \u0026 queer people💗",
      "url": "https://www.materialgrrrlz.com/about-us",
      "contact": {
        "name": "Material Grrrlz",
        "email": null,
        "telephone": null
      }
    }
  }
}
```

Fixes #2474

### CODE REVIEW

**Review by katjam — APPROVED** [review]
Great catch. I am assuming `null: false` means it's not nullable - but we do want it to be.

**Comment by kimadactyl** [comment]
> Great catch. I am assuming `null: false` means it's not nullable - but we do want it to be.

Exactly - one null was erroring out the whole object. Note this means the other end needs to accept `Maybe String` if it doesn't already?

**Comment by honor-gfsc** [comment]
Someone else with more knowledge needs to verify this

**Comment by kimadactyl** [comment]
validated

```
curl -v -H "Content-Type: application/json" -d '{"query": "query { partner(id: 10) { id summary url contact { name email telephone } } }" }' https://placecal-staging.org/api/v1/graphql

->

{"data":{"partner":{"id":"10","summary":"Work for Change provides co-operatively managed workspace including offices, artists studios, workshops, cafe and theatre space. ","url":"","contact":{"name":"","email":"sarah@change.coop","telephone":"0161 226 7696"}}}}
```

**Comment by katjam** [comment]
In the given example, `name` is an empty string. I think this issue was with allowing values to be `null`. Still uncertain why only that one partner saves the values as `null` when the rest are empty string.

> validated
> 
> ```
> curl -v -H "Content-Type: application/json" -d '{"query": "query { partner(id: 10) { id summary url contact { name email telephone } } }" }' https://placecal-staging.org/api/v1/graphql
> 
> ->
> 
> {"data":{"partner":{"id":"10","summary":"Work for Change provides co-operatively managed workspace including offices, artists studios, workshops, cafe and theatre space. ","url":"","contact":{"name":"","email":"sarah@change.coop","telephone":"0161 226 7696"}}}}
> ```

**Pull request merged**
