### PR TITLE
add support section to sidebar in admin ui

### LINKED ISSUE #2146: Make it clear where partners can go for help with tech problems
## User story

As a person running into problems setting up a new calendar or organisation, or feeling something is not quite right, I need to know the paths to common fixes and when to call for help.

Raised off the back of #2094 

## Acceptance Criteria

- [ ] on each page of the admin UI non-root users can access the following:
  - [ ] Link to handbook
  - [ ] Link to support email
  - [ ] Link to Discord
  - [ ] Link to report a bug on Github

## implementation plan

based off Kim and Ivan's suggestions I think we should make use of the sidebar nav to have help available on each page.

For non-root users we can use the space of "In development" and assume that root users are the people who would be giving the help or at least already know how to find resources.

image

### PR DESCRIPTION
**Pull request by aaaaargZombies**
fixes #2146 

Added all the suggested links into the sidebar and moved the report a bug link in there too, I wrote the AC as appearing for admins but I included roots in this too as there seemed no harm in it and being familiar with what other users will see will make it easier to advice / support people.

2024-04-12-11:07:01-screenshot

### CODE REVIEW

**Comment by kimadactyl** [comment]
I think this looks great, my only q is how do people feel about `mailto:` links? I feel like for me they are a bit of very old fashioned tech that often results in my mail client opening and trying to run me through a setup wizard. Maybe it should just be a plain text email address?

**Comment by aaaaargZombies** [comment]
I think the problem of not using `mailto:` in a link in a link tag is an email isn't a valid url and it breaks like this

image


we could just leave it as text?

**Comment by kimadactyl** [comment]
yeah i was advocating for removing the link completely and just tell people the email. fine if others disagree ofc! ive just litearlly never found this function to be welcome personally.

**Comment by katjam** [comment]
Agree with kim. Plan text is perfect and more usable.

**Comment by aaaaargZombies** [comment]
I see! That makes sense, it's implemented now

image

**Comment by kimadactyl** [comment]
this still has the "email us" link in - need to remove?

this looks a bit out of place now - would it make sense to move it into the small text below the build number?

**Comment by aaaaargZombies** [comment]
whoops took the screenshot too soon

you can see it's removed in the code here

```eruby
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Get support</span>
    </h6>
    <%= admin_nav_link('Handbook', 'https://handbook.placecal.org/', 'book')%>
    <li class="nav-item"><span class="nav-link"><i class="fa fa-envelope feather"></i>support@placecal.org</span></li>
    <%= admin_nav_link('Discord', 'http://discord.gfsc.studio/', 'comment')%>
    <%= admin_nav_link('Report a bug', 'https://github.com/geeksforsocialchange/PlaceCal/issues/new?assignees=&labels=&template=bug_report.md', 'bug')%>
```

[view code in context](https://github.com/geeksforsocialchange/PlaceCal/blob/173d692f8d8e3c8103d3c57c2cc5ab30ed265219/app/views/layouts/admin/_admin_navigation.html.erb#L17-L23)

**Comment by aaaaargZombies** [comment]
image

**Comment by aaaaargZombies** [comment]
> also looks a bit out of place in the menu - would it make sense to move it into the small text below the build number?

I really think we should have all the get support stuff in one place not scattered around the shop - I felt "email us" looked more in keeping but as you and Katja say maybe less practical.

**Comment by aaaaargZombies** [comment]
It's in the bottom of the list for non-root users, the bottom of the list is all that stuff that should probably be ignored because we aren't working on it, collections etc.

**Comment by kimadactyl** [comment]
sorry i specifically mean put the email link at the top or bottom of the list - itll prob look a bit more balanced to go "ABBB" than "ABAA"

**Comment by aaaaargZombies** [comment]
OK I think we might be on the home straight

image

**Pull request merged**
