### PR TITLE
Partner hidden warning

### LINKED ISSUE #2364: [Bug]: fix text on partner missing location error message
## Description

Screenshot_2024-04-04_14-12-34

"...This usually means one of *two* things:"

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Closes #2364 #2419

Fixes text

Add warning banner to admins that partner is hidden
Screenshot_2024-04-22_16-07-59

(Copy/Layout TBC)

### CODE REVIEW

**Comment by aaaaargZombies** [comment]
hmmm we're getting a bunch of different states going

This is what partner_admin for the hidden partner sees on `production`

2024-04-23-12:21:48-screenshot

This is what partner_admin for the hidden partner sees on the PR branch, they don't have the power to change moderation status so the link goes nowhere

2024-04-23-12:23:04-screenshot

This is what someone with the power to edit `hidden` status sees on this PR branch

image


It looks like we basically need to show one / the other to the people with the appropriate power

**Comment by ivan-kocienski-gfsc** [comment]
Ahhhh- I think the big green box is about the partner not having any visibility on any sites through neighbourhoods / tags.

But I will fix the `Change This` link to only show when they can.

**Comment by ivan-kocienski-gfsc** [comment]
That's funny because if i set the hidden value then i do not see that warning at all

**Comment by ivan-kocienski-gfsc** [comment]
This is just duplicating behaviour that (should) already exist, so closing

**Pull request closed without merging**
