### PR TITLE
clear homepage content

### LINKED ISSUE #1381: [Bug]: Hamburger menu button does not function at certain screen widths
## Description

I was looking at the Placecal homepage with two browser windows open side by side and the menu wouldn't open

## Steps to reproduce

1. Go to homepage
2. resize screen to between 800px and 600px wide.

I think it is something to do with `.header__menu` class and various `@media` rules.

## What you expected to happen

Menu is accessible at all page widths.

## Platform (if relevant)

firefox, linux

### LINKED ISSUE #1810: Clear out existing "about PlaceCal" home
We want to start with an empty shell.

## Acceptance criteria

- [x] The site home consists of just header and footer
- [ ] Include if it seems easy, if not, shard to it's own issue: The site wrapper / shared across pages (e.g. header, footer) content uses new design system
- [x] The metadata is accurate & present
- [x] Retain header menu as it is 
- [ ] #1823

## Implementation notes & questions
We probably need to be a little more specific about what stays, like do we definitely want to have footer? Not sure if Mark's new design stuff is components only or if there are also layouts.

In terms of the header navigation, we decided to keep it - Kim uses the "Our Story" page a lot. It might not need to be in the navigation after this refresh, but we need the content to be accessible from somewhere.

## Implementation plan

- [ ] 

_To be written by the developer_

### PR DESCRIPTION
**Pull request by aaaaargZombies**
fixes #1810

## Description

- remove all the content under the red X
- update meta tags based on https://socialsharepreview.com/?url=https://placecal.org
- give the header a bit of love, fixes  #1381
-  footer design to come later from Mark
- I have updated the background color / image

## Questions 

- The pull quote wasn't included in the "stuff to remove" image, but feels like it might want to go, this is an `e` issue to remove later but let me know if you think it should go now.

### CODE REVIEW

**Comment by studiosquid** [comment]
There are some changes to the site wrapper if I'm understanding it properly, at least in terms of background image used — but it doesn't impact sizing / position. And it doesn't impact or hold anything up to address later.

**Comment by aaaaargZombies** [comment]
thanks @studiosquid  I must have misread the comments, I'll go take a peek after I figure out why this test is failing

**Comment by aaaaargZombies** [comment]
@studiosquid here's the updated background, I've set it as a background image and to repeat because that's the most robust solution at different sizes. It looked like from your design you'd maybe taken the same image and inserted it twice at either side of the content, scaling it up with the screen. That is probably possible to do but it requires so more heavy rearranging of the page structure and there will be more edge cases to contend with.

My screen at  1920x1080

Screenshot 2023-05-03 at 10-36-53 PlaceCal The Community Calendar

A much larger screen

Screenshot 2023-05-03 at 10-37-43 PlaceCal The Community Calendar

current placecal homepage on same very large screen, you can see why I've set it to repeat.

Screenshot 2023-05-03 at 10-38-09 PlaceCal The Community Calendar

**Review by r-ferrier — APPROVED** [review]
Code-wise this looks good to me!

**Pull request merged**
