### PR TITLE
Remove unused JS dependencies

### PR DESCRIPTION
**Pull request by erbridge**

### CODE REVIEW

**Review by aaaaargZombies — APPROVED** [review]
a satisfying PR

**Comment by kimadactyl** [comment]
Are you sure cocoon isnt in use still? I thought we were using it for the "add a ward" type pickers

**Comment by aaaaargZombies** [comment]
don't worry it's here

https://github.com/geeksforsocialchange/PlaceCal/blob/main/package.json#L8

It looks like someone got the name first on NPM and then someone installed it on placecal by mistake

https://github.com/brentlintner/cocoon

**Comment by erbridge** [comment]
What @aaaaargZombies said.

**Comment by erbridge** [comment]
Nice thing about JS dependencies: you can search the codebase for their name, and if you can't find it in an `import` or `require`, it's almost certainly not used.

**Pull request merged**
