### PR TITLE
ensure node versions don't get out of step in different environments

### LINKED ISSUE #1783: Production build environment differs from staging
## Description
We had an issue releasing to production because of a mismatch in node versions.

## Motivation

Our build environments need to match in order that we can be certain that the released code is identical, so that we can rely on testing in development and staging environments.

It appears that for the testing part of release process, it is using nodenv & the expected version but when it comes to the deploy / dokku release, it is not.

## Mitigated during 0.14.2

- Rolled back expected node version v16.13.1
- Rolled back lint-staged version
- Recreated yarn lock
- Pushed to staging
- Pushed to production

## Consider fixing
- Make sure all environments use the node version configs
- Turn off renovate
- Update INSTALL.md so it does not refer to stuff we no longer use (like travis)
- Think about why dev deps would be installed at all during production build process

### PR DESCRIPTION
**Pull request by r-ferrier**
fixes #1783 

## Description

Adds a line to the releasing document to prompt us to double check the node versions are all in sync before releasing so that we don't run into a problem again with different environments struggling with different set ups.

### CODE REVIEW

**Comment by kimadactyl** [comment]
Is it possible to have the renovate config check this somehow?

**Comment by r-ferrier** [comment]
> Is it possible to have the renovate config check this somehow?

Could be! Will investigate

**Review by kimadactyl — APPROVED** [review]
Approving so as to not block given its a straight improvement

**Comment by r-ferrier** [comment]
Checked up on this this morning and it looks good now. Renovate is now making changes to node in [both the node version and the engines section of the package.json](https://github.com/geeksforsocialchange/PlaceCal/pull/1934), so it should now be the same everywhere on push. Woohoo!

**Pull request merged**
