### PR TITLE
Restrict creating, editing and deleting tags to root users

### LINKED ISSUE #1712: Only roots can edit Tags
## User story

As a PlaceCal root admin, I want to stop anyone else editing Tags, so that we get some stability in the system

## Acceptance criteria

- [ ] Only roots can create, edit and delete Tags

## Implementation plan

_To be written by the developer_

### PR DESCRIPTION
**Pull request by ivan-kocienski-gfsc**
Closes #1712 

Only root users can CRUD tags.

Temporary fix so we can review and define proper granular tag access controls

### CODE REVIEW

**Comment by kimadactyl** [comment]
It should be that root users can create, edit, delete. And that everyone with an account can read? Does this remove everyone's read access?

**Comment by kimadactyl** [comment]
Ugh - it also occurs to me that Partnership Admins can currently edit their partnership from the Tag Edit interface and if we do this then they won't be able to any more right? Maybe katja was right that we do need to do this properly

**Comment by ivan-kocienski-gfsc** [comment]
> It should be that root users can create, edit, delete. And that everyone with an account can read? Does this remove everyone's read access?

We don't have a "read" page. It just links to the edit form. Would be weird to allow them to see the edit form and not allow them to change anything.

I would also recommend taking some time to think about this properly

**Comment by kimadactyl** [comment]
Good point. Yeah ok.

**Comment by katjam** [comment]
Closing as this was a quick fix that prevented use of tags. We're fixing it properly.

**Pull request closed without merging**
